spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: 'jdbc:postgresql://192.168.1.148:5432/parking-control'
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        formatSql: true
        jdbc:
          lob:
              non-contextual-creation: true