spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: 'jdbc:postgresql://localhost:54320/parking-control'
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        formatSql: true
        jdbc:
          lob:
              non-contextual-creation: true
        ddl-auto: true